#!/usr/bin/env node
/* IS THE NOVELTY ARITHMETIC, OR IS IT NOISE?
     node harness/probe_novelty.js [seeds]

   Stated as the design brief for the reactive layer: "constraints allow for
   novelty to emerge and music is novelty arithmetically derived."

   That is a falsifiable claim and this is the instrument for it. A drum lane
   over a four-bar material is a 64-step binary string, and three very different
   things can produce one:

     A LOOP          one bar repeated four times. Perfectly predictable. This is
                     what every genre in this file wrote before kit.poly, and it
                     is what a pattern collapses back to if a mechanism stops
                     firing.
     NOISE           onsets scattered at the same density with no structure.
                     Maximally unpredictable, and musically worthless -- but it
                     is ALSO what a reactive rule layer looks like from the
                     outside if the rules are not actually doing anything a
                     listener could follow. This is the null hypothesis, and it
                     is the one that matters: "deterministic rules watching the
                     pattern" and "random sprinkle" are trivially confusable by
                     ear, so a design that cannot be separated from this control
                     has not earned its place.
     STRUCTURED      neither. Compresses better than noise because it is
                     generated by a rule; compresses worse than a loop because
                     the rule is not "repeat".

   THE MEASURE IS LEMPEL-ZIV COMPLEXITY (LZ76, Kaspar-Schuster), which counts the
   distinct substrings a string must be built from. It is the standard
   information-theoretic measure of algorithmic randomness for exactly this shape
   of data, it needs no model or training, and it is cheap over 64 symbols.
   Reported NORMALISED against the two controls, each built to the SAME DENSITY as
   the lane it is judging -- density alone changes LZ, so comparing a sparse lane
   to a dense control would measure the wrong thing entirely.

       novelty = (LZ(lane) - LZ(loop)) / (LZ(noise) - LZ(loop))

     ~0.0   the lane is a loop
     ~1.0   the lane is indistinguishable from a random sprinkle at that density
     middle it is generated, and the generator is neither trivial nor arbitrary

   There is no "correct" value and this file does not pretend there is one: the
   number is here so that a claim about emergence can be checked instead of
   asserted, and so that a mechanism which quietly degenerates -- to a loop at
   one end, to noise at the other -- says so in a number.

   Two supporting numbers per lane:
     BAR-REPEAT   how often bar k+1 equals bar k. 1.0 is a loop.
     IOI ENTROPY  Shannon entropy over inter-onset intervals, in bits. A loop
                  has a tiny vocabulary of gaps; noise has a flat one.
   ─────────────────────────────────────────────────────────────────────────── */
const fs = require("fs"), path = require("path");
const html = fs.readFileSync(path.resolve(__dirname, "..", "Deckards Orchestrator MK2.html"), "utf8");
const src = html.split("<script>")[1].split("</script>")[0];
global.window = { addEventListener(){}, MK2: null };
global.document = { getElementById: () => ({ addEventListener(){}, textContent: "", value: "1", innerHTML: "" }) };
eval(src + "\n;global.__stream = stream;");
const M = global.window.MK2;
const stream = global.__stream;          // the program's own seeded RNG, so the controls reproduce
const N = parseInt(process.argv[2], 10) || 20;
const LEN = 64;                          // 4 bars x 16 steps

/* ── LEMPEL-ZIV 76 COMPLEXITY, the Kaspar-Schuster production count.
   Walks the string maintaining a prefix that has already been "seen" and counts
   how many times it has to start a new production because the next piece cannot
   be copied from what came before. */
function lz76(s){
  const n = s.length;
  if(n === 0) return 0;
  let c = 1, l = 1, i = 0, k = 1, kmax = 1;
  for(;;){
    if(l + k > n){ c++; break; }
    if(s[i + k - 1] === s[l + k - 1]){
      k++;
    } else {
      if(k > kmax) kmax = k;
      i++;
      if(i === l){
        c++;
        l += kmax;
        if(l >= n) break;
        i = 0; k = 1; kmax = 1;
      } else {
        k = 1;
      }
    }
  }
  return c;
}

/* the LOOP control: this lane's FIRST BAR, repeated for the whole material. The
   honest "what if the mechanism did nothing" baseline, because a bar-locked lane
   is exactly what this program wrote before any of this existed. */
function loopControl(bits){
  const out = new Array(LEN);
  for(let i = 0; i < LEN; i++) out[i] = bits[i % 16];
  return out;
}
/* the NOISE control: the same NUMBER of onsets, placed by a seeded shuffle.
   Same density, no structure -- which is the null hypothesis this whole probe
   exists to reject. Seeded off the lane's own content so it is reproducible and
   so two different lanes do not share a control. */
function noiseControl(bits, tag){
  const k = bits.reduce((a, b) => a + b, 0);
  const rng = stream(1, "novelty:" + tag + ":" + k);
  const idx = [];
  for(let i = 0; i < LEN; i++) idx.push(i);
  /* Fisher-Yates on the program's own stream */
  for(let i = LEN - 1; i > 0; i--){
    const j = Math.floor(rng() * (i + 1)) % (i + 1);
    const t = idx[i]; idx[i] = idx[j]; idx[j] = t;
  }
  const out = new Array(LEN).fill(0);
  for(let i = 0; i < k; i++) out[idx[i]] = 1;
  return out;
}

function barRepeat(bits){
  let same = 0, n = 0;
  for(let b = 1; b < 4; b++){
    n++;
    let eq = true;
    for(let s = 0; s < 16; s++) if(bits[b * 16 + s] !== bits[(b - 1) * 16 + s]){ eq = false; break; }
    if(eq) same++;
  }
  return n ? same / n : 0;
}
function ioiEntropy(bits){
  const on = [];
  for(let i = 0; i < LEN; i++) if(bits[i]) on.push(i);
  if(on.length < 3) return 0;
  const counts = {};
  for(let i = 1; i < on.length; i++){ const d = on[i] - on[i - 1]; counts[d] = (counts[d] || 0) + 1; }
  const tot = on.length - 1;
  let h = 0;
  for(const d in counts){ const p = counts[d] / tot; h -= p * Math.log2(p); }
  return h;
}

/* every drum lane of every material as a 64-step binary string */
function lanes(song){
  const out = [];
  for(const m of ["A", "Avar", "B", "C"]){
    const notes = (song.materials[m] || {}).drums;
    if(!notes) continue;
    const byLane = {};
    for(const n of notes){
      if(!byLane[n.lane]) byLane[n.lane] = new Array(LEN).fill(0);
      const at = n.bar * 16 + n.step;
      if(at >= 0 && at < LEN) byLane[n.lane][at] = 1;
    }
    for(const lane in byLane){
      const bits = byLane[lane];
      const k = bits.reduce((a, b) => a + b, 0);
      /* a lane with almost nothing on it, or almost everything, has no room to
         be structured or unstructured -- LZ on 2 onsets is noise in the
         measurement, not in the music */
      if(k < 4 || k > LEN - 4) continue;
      out.push({ lane, m, bits });
    }
  }
  return out;
}

const genres = M.genres();
console.log(`novelty: is the pattern a loop, noise, or generated? — ${N} seeds a genre\n`);
console.log("  0.00 = a bar-locked loop      1.00 = a random sprinkle at the same density\n");
console.log("  genre          lanes   novelty   bar-repeat   IOI bits   density");

const rows = {};
for(const g of genres){
  let nov = 0, rep = 0, ent = 0, den = 0, n = 0;
  for(let s = 1; s <= N; s++){
    for(const L of lanes(M.composeSong(s, undefined, g))){
      const a = lz76(L.bits), lo = lz76(loopControl(L.bits)), hi = lz76(noiseControl(L.bits, g + ":" + L.lane));
      /* if the two controls collapse onto each other the lane is too sparse or
         too dense for the measure to say anything -- skip rather than divide by
         a number near zero and report a spike */
      if(hi - lo < 1) continue;
      nov += (a - lo) / (hi - lo);
      rep += barRepeat(L.bits);
      ent += ioiEntropy(L.bits);
      den += L.bits.reduce((x, y) => x + y, 0) / LEN;
      n++;
    }
  }
  if(!n){ console.log(`  ${g.padEnd(13)} ${String(0).padStart(6)}        --`); continue; }
  rows[g] = { nov: nov / n, rep: rep / n, ent: ent / n, den: den / n, n };
  const r = rows[g];
  console.log(`  ${g.padEnd(13)} ${String(r.n).padStart(6)}    ${r.nov.toFixed(3).padStart(6)}       ` +
              `${r.rep.toFixed(3).padStart(6)}     ${r.ent.toFixed(2).padStart(6)}    ${r.den.toFixed(3)}`);
}

console.log("\n  reading it:");
console.log("    novelty near 0 with bar-repeat near 1  -> the lane is a loop and nothing is generating");
console.log("    novelty near 1                          -> indistinguishable from a random sprinkle,");
console.log("                                               which no rule-based claim survives");
console.log("    novelty 0.2-0.7 with bar-repeat low     -> generated, and the generator is doing work");

/* THE DETERMINISM HALF, because none of the above means anything if the same
   seed gives a different pattern: "novelty arithmetically derived" is a claim
   about ARITHMETIC, and arithmetic repeats. */
let drift = 0, checked = 0;
for(const g of genres) for(let s = 1; s <= 6; s++){
  const a = lanes(M.composeSong(s, undefined, g)).map(x => x.lane + ":" + x.bits.join("")).join("|");
  const b = lanes(M.composeSong(s, undefined, g)).map(x => x.lane + ":" + x.bits.join("")).join("|");
  checked++; if(a !== b) drift++;
}
console.log(`\n  ${drift === 0 ? "OK" : "BAD"}: the same seed writes the same pattern  (${checked - drift}/${checked})`);
