#!/usr/bin/env node
/* PROBE_BANK — DOES EVERY RECORDED SAMPLE ACTUALLY DECODE TO SOUND?

     node harness/probe_bank.js

   WHY THIS EXISTS, and it is the second-most expensive lesson in this file.

   `harness/fiddle_bank.py` wrote SAMPLE offsets into the bank index where every
   other encoder in this directory writes BYTE offsets. The reader indexes the
   blob as `bin.charCodeAt(s.off + (i >> 1))` -- `off` addresses bytes, `i`
   counts samples, two samples to a byte -- so every address was doubled.

   The result: 37 of 75 rows pointed PAST THE END of the payload and decoded to
   silence, and the other 38 decoded the wrong note. A whole instrument and a
   whole percussion set shipped as noise and nothing.

   AND EVERY CHECK PASSED. The battery was green. `probe_rack` said the panel
   named a box that played. `probe_reachable` said every configured name
   happens. `probe_controls` said all five of its knobs moved the sound -- it
   renders a note and compares two settings, and two settings of silence differ
   by 0 dB, which it reads as "no travel" on some knobs and, through the filter
   sweep, as movement on others. The composer knew the fiddle was drawn, the
   arranger knew it was playing, stage 5 knew how long a bow lasts. Not one of
   them asks whether the AUDIO IS THERE.

   That is the hole this fills, and it is deliberately the cheapest possible
   version of it: no rendering, no graph, no browser. Decode every sample in
   every bank and ask three questions of the numbers.

     IN RANGE   does the row address a region the payload actually contains?
     NOT SILENT does the decoded audio have any energy at all?
     NOT CLIPPED is it decoding as data rather than as garbage? ADPCM fed the
                wrong bytes runs its step index to the ceiling and pins at full
                scale, so a sample that is almost entirely at +-1.0 is a
                misread, not a loud recording.
     IN TUNE    does a row that declares a root actually SOUND at that root?

   THE FOURTH ONE IS THE IMPORTANT ONE and it was added after watching the
   first three run against the broken bank: they caught the 37 rows that read
   past the end, and MISSED ALL 38 that read the wrong bytes -- those decode to
   perfectly healthy audio, just of the wrong note. Silence is loud; a wrong
   note is quiet.

   Every pitched encoder in this directory MEASURES its roots by autocorrelation
   and drops anything more than 60 cents from its filename. That rule is
   enforced at WRITE time and was never checked at read time, so an index that
   addressed the wrong audio kept its correct-looking root column. Measuring the
   decoded audio and comparing it to the root the row claims closes the loop:
   the two halves of the bank now have to agree about what the note is.

   A bank is a payload plus an index, and the index is hand-generated by a
   script per pack. This is the one check that says the two agree. */
const fs = require("fs");
const path = require("path");
/* a path may be passed so this check can be RUN AGAINST A KNOWN-BROKEN COPY --
   a guard nobody has watched fail is a guard nobody knows works */
const HTML = process.argv[2] || path.resolve(__dirname, "..", "Boxcar Synth.html");
const src = fs.readFileSync(HTML, "utf8").split("<script>")[1].split("</script>")[0];
global.window = { addEventListener(){}, MK2: null };
global.document = { getElementById: () => ({ addEventListener(){}, textContent: "", value: "1", innerHTML: "" }),
                    createElement: () => ({ click(){} }) };
eval(src + ";global.__BANK = ERANG;");
const ERANG = global.__BANK;

/* THE PITCH OF A DECODED SAMPLE, by autocorrelation on its steady middle —
   the same method every encoder in this directory uses to decide a root, run
   on the other side of the index so the two can be compared. */
function measureHz(x, rate, lo, hi){
  let a = Math.floor(x.length * 0.30), b = Math.floor(x.length * 0.70);
  if(b - a < 2048){ a = 0; b = x.length; }
  const n = b - a;
  let mean = 0;
  for(let i = a; i < b; i++) mean += x[i];
  mean /= n;
  const loLag = Math.max(2, Math.floor(rate / hi)), hiLag = Math.min(n - 1, Math.floor(rate / lo));
  if(hiLag <= loLag) return 0;
  /* NORMALISED, not raw. Raw autocorrelation grows with the energy inside the
     window, which biases every comparison toward SHORT lags and is why the
     first version of this needed an octave fold to make sense at all. */
  const corr = new Float64Array(hiLag + 1);
  for(let lag = loLag; lag <= hiLag; lag++){
    let s = 0, e1 = 0, e2 = 0;
    for(let i = a; i + lag < b; i++){
      const u = x[i] - mean, v = x[i + lag] - mean;
      s += u * v; e1 += u * u; e2 += v * v;
    }
    corr[lag] = (e1 > 0 && e2 > 0) ? s / Math.sqrt(e1 * e2) : 0;
  }
  let bestLag = 0, bestV = -Infinity;
  for(let lag = loLag; lag <= hiLag; lag++)
    if(corr[lag] > bestV){ bestV = corr[lag]; bestLag = lag; }
  if(!bestLag) return 0;
  /* ── SUBHARMONIC REJECTION, and it is the whole reason this is not four
     lines ────────────────────────────────────────────────────────────────
     A period of T also correlates at 2T and 3T, so a reedy tone — a harmonica,
     a banjo — routinely peaks an octave or a fifth BELOW its own fundamental.
     Ten good samples were reported as 168 to 666 cents out by the naive
     version, and every one of them was this. The fix is the standard one:
     prefer the SHORTEST lag whose correlation is nearly as good as the peak's,
     because that is the true period and the longer ones are its multiples. */
  for(let k = 4; k >= 2; k--){
    const cand = Math.round(bestLag / k);
    if(cand >= loLag && corr[cand] > bestV * 0.85){ bestLag = cand; break; }
  }
  return rate / bestLag;
}

let pass = 0, fail = 0;
const bad = { range: [], silent: [], pinned: [], tune: [] };
const perFam = {};

for(const name of ERANG.names){
  const m = ERANG.meta(name);
  const fam = perFam[m.fam] = perFam[m.fam] || { n: 0, bad: 0, rms: 0 };
  fam.n++;
  let pcm = null;
  try { pcm = ERANG.pcm(name); } catch(e){ pcm = null; }
  /* IN RANGE. `pcm()` reads charCodeAt past the end as NaN, which propagates
     to a silent buffer rather than throwing -- so this is checked by the
     numbers, not by whether the call survived. */
  if(!pcm || !pcm.length || !Number.isFinite(pcm[pcm.length - 1])){
    bad.range.push(name + " (" + m.fam + ")"); fam.bad++; fail++; continue;
  }
  let sum = 0, pinned = 0, peak = 0;
  for(let i = 0; i < pcm.length; i++){
    const v = pcm[i];
    if(!Number.isFinite(v)){ pinned = pcm.length; break; }
    sum += v * v; const a = Math.abs(v);
    if(a > peak) peak = a;
    if(a > 0.995) pinned++;
  }
  const rms = Math.sqrt(sum / pcm.length);
  fam.rms += rms;
  if(rms < 1e-5){ bad.silent.push(name + " (" + m.fam + ")"); fam.bad++; fail++; continue; }
  /* over a fifth of the samples at full scale is not a recording */
  if(pinned / pcm.length > 0.20){
    bad.pinned.push(name + " (" + m.fam + ", " + (100 * pinned / pcm.length).toFixed(0) + "% at full scale)");
    fam.bad++; fail++; continue;
  }
  /* IN TUNE. Only rows that CLAIM a root — a drum, a scrape and a station's
     room tone declare 0 and are not asked a question they have no answer to.
     The window is 120 cents, wider than the 60 the encoders enforce, because
     autocorrelation on a decoded 4-bit stream is a coarser instrument than the
     one that ran on the 16-bit original. It is still an order of magnitude
     tighter than "this is a different note". */
  if(m.root > 0){
    const hz = measureHz(pcm, ERANG.rate, m.root * 0.55, m.root * 1.8);
    const cents = hz > 0 ? 1200 * Math.log2(hz / m.root) : 9999;
    if(Math.abs(cents) > 120){
      bad.tune.push(name + " (" + m.fam + ", says " + m.root.toFixed(1) +
                    " Hz, sounds " + (hz > 0 ? hz.toFixed(1) : "?") + " Hz, " +
                    (cents === 9999 ? "no pitch found" : Math.round(cents) + " cents off") + ")");
    }
  }
  pass++;
}

console.log("\n=== EVERY SAMPLE IN EVERY BANK, DECODED\n");
console.log("  family            samples   unusable   mean rms");
for(const f of Object.keys(perFam).sort()){
  const a = perFam[f];
  console.log("  " + f.padEnd(18) + String(a.n).padStart(6) + String(a.bad).padStart(11) +
              "   " + (a.rms / Math.max(1, a.n - a.bad)).toFixed(4));
}
console.log("");
const say = (label, list) => {
  if(!list.length){ console.log("  ✓ " + label); return; }
  console.log("  ✗ FAIL: " + label + "  (" + list.length + ")");
  for(const x of list.slice(0, 12)) console.log("        " + x);
  if(list.length > 12) console.log("        ...and " + (list.length - 12) + " more");
};
say("every row addresses audio the payload actually holds", bad.range);
say("every sample decodes to something audible", bad.silent);
say("no sample decodes as pinned garbage", bad.pinned);
/* ── AND THIS ONE REPORTS, IT DOES NOT ASSERT ─────────────────────────────
   Run against the broken bank it names 39 more rows than the three checks
   above; run against the CORRECT bank it still names eight, all of them
   harmonica or banjo, all off by a fifth or an octave. Those may be genuine
   mis-rooted rows in packs encoded by a different script, or they may be this
   estimator meeting a reedy tone it cannot read. I do not know which, and the
   only way to make the number zero today would be to widen the window until it
   passed -- which is a test whose bar moves to fit the code, i.e. no test.

   So: printed, never asserted, and written down as work rather than tuned
   away. The three checks above catch the class of bug that actually shipped;
   this one is intelligence until somebody settles the eight. */
if(bad.tune.length){
  console.log("\n  ‣ REPORT (not a failure): " + bad.tune.length +
              " samples do not sound at the root their row claims");
  for(const x of bad.tune.slice(0, 12)) console.log("        " + x);
  if(bad.tune.length > 12) console.log("        ...and " + (bad.tune.length - 12) + " more");
} else {
  console.log("  ‣ every sample that declares a root sounds at that root");
}
console.log("\n  " + pass + " samples usable, " + fail + " not\n");
process.exit(fail ? 1 : 0);
