#!/usr/bin/env node
/* CHROMATICISM AND VOICE LEADING, read off the chords.
     node harness/probe_harmony_neo.js [seeds]

   The handoff named this the ceiling: every genre measured 0.0% out-of-key
   notes, "the law working and also a ceiling -- no secondary dominants, no
   borrowed chords, no chromatic passing tones. Nothing in the program can
   currently write one." Neo-Riemannian transformations are one way through it,
   and they make two claims that can be checked separately:

     CHROMATIC   share of chords containing a pitch class the mode does not.
                 0.0% is the old ceiling. It should be non-zero only for the
                 genres that ASK for it -- a genre with no `harmony` block must
                 measure exactly what it measured before.
     VOICE LEAD  mean semitones moved, summing each voice's smallest motion to
                 the next chord. This is the point of P, L and R rather than a
                 side effect: each moves ONE voice by a semitone or a tone, so
                 if the transformations are wired correctly the chromatic
                 progressions should move LESS than the diatonic ones, not more.
                 A chromatic progression that also lurches is a bug.

   Both are rates. Neither is a pass/fail on one song. */
const fs = require("fs"), path = require("path");
const html = fs.readFileSync(path.resolve(__dirname, "..", "Deckards Orchestrator MK2.html"), "utf8");
const src = html.split("<script>")[1].split("</script>")[0];
global.window = { addEventListener(){}, MK2: null };
global.document = { getElementById: () => ({ addEventListener(){}, textContent: "", value: "1", innerHTML: "" }) };
eval(src + ";global.__T = { MODES };");
const M = global.window.MK2, MODES = global.__T.MODES;
const N = parseInt(process.argv[2], 10) || 60;
const pc = m => ((m % 12) + 12) % 12;

/* the smallest total motion from one chord to the next, voice by voice: for
   each tone of A, the distance to the nearest tone of B, averaged. */
function lead(a, b){
  let sum = 0;
  for(const t of a){
    let best = 99;
    for(const u of b){
      const d = Math.min(pc(u - t), pc(t - u));
      if(d < best) best = d;
    }
    sum += best;
  }
  return sum / a.length;
}

console.log("chords, " + N + " seeds a genre\n");
console.log("  genre        chromatic chords   voice leading (semitones)   distinct progressions");
for(const g of M.genres()){
  let chrom = 0, tot = 0, leadSum = 0, leadN = 0;
  const seen = new Set();
  for(let s = 1; s <= N; s++){
    const song = M.composeSong(s, "band", g);
    const { root, mode } = song.chart;
    const cs = song.materials.chords;
    seen.add(cs.map(c => c.tones.map(pc).join(".")).join("|"));
    for(let i = 0; i < cs.length; i++){
      tot++;
      if(cs[i].tones.some(t => !MODES[mode].includes(pc(t - root)))) chrom++;
      leadSum += lead(cs[i].tones, cs[(i + 1) % cs.length].tones); leadN++;
    }
  }
  console.log(`  ${g.padEnd(12)} ${(100 * chrom / tot).toFixed(1).padStart(8)}%          ` +
              `${(leadSum / leadN).toFixed(2).padStart(6)}                ${String(seen.size).padStart(4)}`);
}

/* PRINT SOME, because a table is not the chords */
const NAMES = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
console.log("\n" + "─".repeat(72));
console.log("vgm — the first seeds whose harmony is generated by transformation:");
let shown = 0;
for(let s = 1; s <= 200 && shown < 6; s++){
  const song = M.composeSong(s, "band", "vgm");
  const { root, mode } = song.chart;
  const cs = song.materials.chords;
  if(!cs.some(c => c.tri)) continue;
  shown++;
  const nm = c => {
    const r = c.tri ? c.tri.pc : null;
    const third = pc(c.tones[1] - (r == null ? c.tones[0] : r));
    return NAMES[r == null ? pc(c.tones[0]) : r] + (third === 3 ? "m" : "");
  };
  const outside = cs.filter(c => c.tones.some(t => !MODES[mode].includes(pc(t - root)))).length;
  console.log(`  seed ${String(s).padStart(3)}  ${NAMES[root]} ${mode.padEnd(10)} ` +
              cs.map(nm).join(" → ").padEnd(24) +
              `  ${outside}/4 chords leave the key   voice lead ` +
              (cs.map((c, i) => lead(c.tones, cs[(i + 1) % cs.length].tones))
                 .reduce((a, b) => a + b, 0) / cs.length).toFixed(2));
}
if(!shown) console.log("  (none in the first 200 seeds — check the `harmony` block)");
