/**
 * The instruments. Each renders one note into a buffer from its pitch, its
 * length, its weight and a seed — and nothing else, so a note is the same
 * note wherever it falls in the record.
 *
 * The recipes are the published ones and the numbers are theirs:
 *
 *   rhodes  FM tine piano. A carrier with a 1:1 modulator for the body, and
 *           a bright modulator near 14:1 whose level decays in tens of
 *           milliseconds — that is the tine (pluginboutique.com, "FM
 *           Synthesis Cookbook"; attackmagazine.com, "FM Electric Piano").
 *   wurly   FM REED piano, and the ratios are the whole difference. A
 *           Wurlitzer is not a darker Rhodes: "sound is generated by striking
 *           a metal reed with a hammer", where a Rhodes strikes a tine, and
 *           the result is "sharper and closer to a sawtooth wave" against the
 *           Rhodes's sine (en.wikipedia.org/wiki/Wurlitzer_electronic_piano).
 *           A 3:1 body modulator puts energy in the low odd partials where
 *           1:1 leaves a sine, and 7:1 is the reed's front where the Rhodes
 *           has a 14:1 tine. Hard playing gives "a characteristic slightly
 *           overdriven tone usually described as a 'bark'" (the same), which
 *           is the index and the saturation both following the weight.
 *   sub     a sine with a little second harmonic, a warm sub bass.
 *   pluck   a Karplus–Strong string, muted: a noise burst through a delay
 *           line with a lowpass in the loop.
 *   kick    a sine near 58 Hz under a pitch envelope decaying in about 50 ms
 *           (modeaudio.com, "Drum Synth Sound Design: Kick & Snare").
 *   snare   a sine near 200 Hz, filtered noise, and a click of a few ms
 *           (the same).
 *   hat     narrow-band noise, closed short and open long.
 *   organ   additive, the drawbar way: sines at the sub-octave, the
 *           fundamental, the octave, the twelfth and the fifteenth
 *           (soundonsound.com, "Synthesizing Tonewheel Organs").
 *   pad     two sawtooths a few cents apart under a lowpass, with a slow
 *           attack and a long release (soundonsound.com, "Synthesizing
 *           Strings"; attackmagazine.com, "Detuned Pad").
 *   flute   a sine with a little second harmonic, breath noise, and vibrato
 *           (soundonsound.com, "Practical Flute Synthesis").
 */

import { Biquad, Noise, decayPerSample, envelope, fade, midiHz, saturate, sinTurns, tailSec, type Shape } from "./dsp.ts";

/**
 * DOES THIS VOICE HOLD A NOTE, or is it struck and gone?
 *
 * The shapes below say it and nothing outside this file could know it: the
 * Rhodes settles at 0.08 of its peak and the pluck is a string decaying in a
 * delay line, so a note written to last four bars is inaudible long before the
 * bar line. The organ holds at 1, the flute at 0.9, the pad at 0.85 and the
 * sub at 0.6 — all of them still there when the note ends.
 *
 * It is here because it is a fact about the VOICE. `treat.ts` asks it before
 * lending one part's instrument to another: a drone holds a whole statement,
 * and handing it a struck voice does not re-orchestrate the line, it deletes
 * it.
 */
export const HOLDS: Readonly<Record<string, boolean>> = Object.freeze({
  rhodes: false, pluck: false, wurly: false,
  sub: true, organ: true, pad: true, flute: true,
});

export interface NoteIn {
  readonly midi: number;
  readonly heldSec: number;
  /** 0..1.25 */
  readonly gain: number;
  readonly seed: number;
  readonly sampleRate: number;
}

const buffer = (sec: number, sr: number): Float32Array => new Float32Array(Math.max(1, Math.ceil(sec * sr)));

/**
 * A held note's buffer: the note, then long enough for its release to fall
 * away. Derived from the shape rather than a number picked per voice, so a
 * voice cannot be given a long release and a short buffer to put it in.
 */
const held = (n: NoteIn, sh: Shape): Float32Array => buffer(n.heldSec + tailSec(sh.releaseSec), n.sampleRate);

const RHODES: Shape = { attackSec: 0.003, decaySec: 1.6, sustain: 0.08, releaseSec: 0.09 };

export function rhodes(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, RHODES);
  const heldSamples = Math.round(n.heldSec * sr);
  // harder notes have more tine: the index follows the weight. Both
  // indices decay by a multiplier a sample, as does the amplitude; the
  // phases accumulate in turns, so the sine is a table lookup
  let iBody = 0.9 * n.gain;
  let iTine = 1.1 * n.gain;
  const kBody = decayPerSample(0.7, sr);
  const kTine = decayPerSample(0.06, sr);
  const kDecay = decayPerSample(RHODES.decaySec, sr);
  const kRelease = decayPerSample(RHODES.releaseSec, sr);
  const attack = Math.max(1, Math.round(RHODES.attackSec * sr));
  let decay = 1;
  let release = 1;
  const dPhase = f / sr;
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const a = i < attack ? i / attack : 1;
    decay *= kDecay;
    if (i > heldSamples) release *= kRelease;
    const env = a * (RHODES.sustain + (1 - RHODES.sustain) * decay) * release;
    if (env < 1e-4 && i > heldSamples) break;
    const mod = iBody * sinTurns(phase) + iTine * sinTurns(phase * 14);
    out[i] = sinTurns(phase + mod / (2 * Math.PI)) * env * 0.5;
    phase += dPhase;
    iBody *= kBody;
    iTine *= kTine;
  }
  return fade(out, sr);
}

/**
 * THE WURLITZER, ported from MKII — and one part of it deliberately left behind.
 *
 * MKII's `V.wurly` is the same instrument in Web Audio nodes, and the shape of
 * it carries over unchanged: a body pair at 3:1, a reed front at 7:1 with its
 * own short life, and a lowpass that starts open and closes over about 300 ms.
 * The ratios and the filter's endpoints are MKII's own numbers and are marked
 * as ported rather than re-derived.
 *
 * WHAT DOES NOT COME OVER IS THE TREMOLO, and the reason is a fact about THIS
 * program rather than about the instrument. The 200A has one — its circuit
 * "oscillates at approximately 6 Hz" with a fixed rate and an adjustable depth
 * (Wurlitzer 200A/206A service notes, as cited in MKII) — and MKII could run
 * it inside the voice because a note there was rendered at an absolute time on
 * a running clock, so the LFO was continuous across the record.
 *
 * MKIII renders a note ONCE and reuses it wherever it recurs — `render.ts`
 * caches by pitch, length, velocity layer and articulation — and `NoteIn`
 * carries no absolute time. An LFO written in here would therefore restart at
 * phase zero on every note and be bit-identical in every occurrence: an
 * amplitude envelope wearing a tremolo's name, which is this program's
 * cardinal sin with an extra step. The cache is an accident of how MKIII
 * renders, not a law — but it is load-bearing, and the honest place for a
 * continuous 5–6 Hz amplitude sweep in MKIII is the desk, where the tremolo
 * pedal already runs on the record's own clock and lofi already walks it.
 *
 * So: the reed and the bark are the voice's, and the tremolo is the board's.
 */
const WURLY: Shape = { attackSec: 0.003, decaySec: 1.1, sustain: 0.12, releaseSec: 0.18 };

export function wurly(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, WURLY);
  const heldSamples = Math.round(n.heldSec * sr);
  // the body's index and the reed's, both following the weight: how hard the
  // reed is being hit is the whole of the Wurlitzer's expression
  let iBody = 0.55 + 0.85 * n.gain;
  let iReed = 1.9 * (0.25 + 0.75 * n.gain);
  const kBody = decayPerSample(0.9, sr);
  // the reed's front is shorter than a Rhodes tine's and louder while it lasts
  const kReed = decayPerSample(0.11, sr);
  const kDecay = decayPerSample(WURLY.decaySec, sr);
  const kRelease = decayPerSample(WURLY.releaseSec, sr);
  const attack = Math.max(1, Math.round(WURLY.attackSec * sr));
  // MKII's sweep: open on the strike, closing to about half over 300 ms
  const wide = 2400 + 3600 * n.gain;
  const closed = 1400 + 1600 * n.gain;
  const lp = new Biquad("lowpass", wide, 0.4, sr);
  const kOpen = decayPerSample(0.3, sr);
  let open = 1;
  // the sweep is retuned in blocks rather than per sample: recomputing a
  // biquad's coefficients costs two trig calls, and over a 300 ms glide a
  // block of 64 moves the cutoff by well under a cent of its travel
  const RETUNE = 64;
  let decay = 1;
  let release = 1;
  const dPhase = f / sr;
  let phase = 0;
  // "a characteristic slightly overdriven tone usually described as a bark":
  // only the hard notes reach it, so the drive follows the weight and a quiet
  // note passes through very nearly clean
  const drive = 1 + 1.6 * n.gain * n.gain;
  for (let i = 0; i < out.length; i++) {
    const a = i < attack ? i / attack : 1;
    decay *= kDecay;
    if (i > heldSamples) release *= kRelease;
    const env = a * (WURLY.sustain + (1 - WURLY.sustain) * decay) * release;
    if (env < 1e-4 && i > heldSamples) break;
    open *= kOpen;
    if (i % RETUNE === 0) lp.set("lowpass", closed + (wide - closed) * open, 0.4, sr);
    const mod = iBody * sinTurns(phase * 3) + iReed * sinTurns(phase * 7);
    const y = sinTurns(phase + mod / (2 * Math.PI));
    out[i] = lp.run(saturate(y, drive) / drive) * env * 0.62;
    phase += dPhase;
    iBody *= kBody;
    iReed *= kReed;
  }
  return fade(out, sr);
}

const SUB: Shape = { attackSec: 0.006, decaySec: 0.8, sustain: 0.6, releaseSec: 0.05 };

export function sub(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, SUB);
  const twoPi = 2 * Math.PI;
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const env = envelope(t, n.heldSec, SUB);
    if (env < 1e-4 && t > n.heldSec) break;
    const second = 0.25 * Math.exp(-t / 0.25);
    out[i] = (Math.sin(twoPi * f * t) + second * Math.sin(twoPi * 2 * f * t)) * env * 0.7;
  }
  return fade(out, sr);
}

export function pluck(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const period = Math.max(2, Math.round(sr / f));
  // the loop's own loss decides how long a string rings, not a shape
  const out = buffer(n.heldSec + tailSec(0.12), sr);
  const noise = new Noise(n.seed);
  const line = new Float32Array(period);
  for (let i = 0; i < period; i++) line[i] = noise.next();
  // the mute: a lowpass in the loop takes the top off fast, and the loss
  // makes the string die on its own
  const loss = 0.992;
  let idx = 0;
  let prev = 0;
  const damp = new Biquad("lowpass", 2400, 0.7, sr);
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const cur = line[idx]!;
    const next = line[(idx + 1) % period]!;
    const avg = (cur + next) * 0.5 * loss;
    line[idx] = avg;
    idx = (idx + 1) % period;
    // let go: the loop damps harder once the note is released
    const rel = t > n.heldSec ? Math.exp(-(t - n.heldSec) / 0.05) : 1;
    const y = damp.run(avg) * rel;
    // a muted string is quiet by nature; brought up to sit with the others,
    // and held under full scale, since the burst's peak is the seed's
    out[i] = Math.tanh((y + prev) * 0.5 * 2.9 * (0.5 + 0.5 * n.gain));
    prev = y;
    if (t > n.heldSec && Math.abs(y) < 1e-4 && i > period * 4) break;
  }
  return fade(out, sr);
}

/** The kick's body decays with this time constant; the buffer follows it. */
const KICK_TAU = 0.22;

export function kick(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const out = buffer(tailSec(KICK_TAU), sr);
  const twoPi = 2 * Math.PI;
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    // the pitch falls from a clicky start onto the body in about 50 ms
    const hz = 58 + 140 * Math.exp(-t / 0.05);
    phase += (twoPi * hz) / sr;
    const env = Math.exp(-t / KICK_TAU) * (t < 0.001 ? t / 0.001 : 1);
    out[i] = Math.tanh(Math.sin(phase) * 2.2) * env * 0.95 * n.gain;
  }
  return fade(out, sr);
}

/** The rattle outlasts the tone, so it sizes the buffer. */
const SNARE_TAU = 0.13;

export function snare(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const out = buffer(tailSec(SNARE_TAU), sr);
  const twoPi = 2 * Math.PI;
  const noise = new Noise(n.seed);
  const band = new Biquad("bandpass", 1800, 0.7, sr);
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const tone = Math.sin(twoPi * 200 * t) * Math.exp(-t / 0.08);
    const rattle = band.run(noise.next()) * Math.exp(-t / SNARE_TAU);
    const click = t < 0.004 ? noise.next() * (1 - t / 0.004) : 0;
    out[i] = (0.55 * tone + 1.6 * rattle + 0.5 * click) * n.gain * 0.6;
  }
  return fade(out, sr);
}

export function hat(n: NoteIn, open: boolean): Float32Array {
  const sr = n.sampleRate;
  const tau = open ? 0.12 : 0.025;
  const out = buffer(tailSec(tau), sr);
  const noise = new Noise(n.seed);
  const hp = new Biquad("highpass", 7000, 0.8, sr);
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    out[i] = hp.run(noise.next()) * Math.exp(-t / tau) * 0.6 * n.gain;
  }
  return fade(out, sr);
}

const ORGAN: Shape = { attackSec: 0.02, decaySec: 4, sustain: 1, releaseSec: 0.12 };
/** Drawbars: [harmonic ratio, level]. 16', 8', 4', 2⅔', 2'. */
const DRAWBARS: readonly (readonly [number, number])[] = [[0.5, 0.5], [1, 1], [2, 0.6], [3, 0.35], [4, 0.25]];

export function organ(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, ORGAN);
  const phases = DRAWBARS.map(() => 0);
  const norm = 0.8 / DRAWBARS.reduce((a, [, l]) => a + l, 0);
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const env = envelope(t, n.heldSec, ORGAN);
    if (env < 1e-4 && t > n.heldSec) break;
    let y = 0;
    for (let k = 0; k < DRAWBARS.length; k++) {
      const [ratio, level] = DRAWBARS[k]!;
      y += level * sinTurns(phases[k]!);
      phases[k] = phases[k]! + (f * ratio) / sr;
    }
    out[i] = y * norm * env * (0.6 + 0.4 * n.gain);
  }
  return fade(out, sr);
}

const PAD: Shape = { attackSec: 0.35, decaySec: 3, sustain: 0.85, releaseSec: 0.9 };

export function pad(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, PAD);
  // seven cents apart, one each side, a third saw an octave down for weight
  const detune = Math.pow(2, 7 / 1200);
  const d = [f * detune, f / detune, f / 2].map((hz) => hz / sr);
  const ph = [0, 0.37, 0.61];
  const lp = new Biquad("lowpass", Math.min(2600, f * 6), 0.8, sr);
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const env = envelope(t, n.heldSec, PAD);
    if (env < 1e-4 && t > n.heldSec) break;
    let y = 0;
    for (let k = 0; k < 3; k++) {
      // a sawtooth as a phase ramp; naive, and the lowpass takes the top off
      y += (k === 2 ? 0.5 : 1) * (2 * ph[k]! - 1);
      ph[k] = ph[k]! + d[k]!;
      if (ph[k]! >= 1) ph[k] = ph[k]! - 1;
    }
    out[i] = lp.run(y) * 0.34 * env * (0.6 + 0.4 * n.gain);
  }
  return fade(out, sr);
}

const FLUTE: Shape = { attackSec: 0.06, decaySec: 2, sustain: 0.9, releaseSec: 0.12 };

export function flute(n: NoteIn): Float32Array {
  const sr = n.sampleRate;
  const f = midiHz(n.midi);
  const out = held(n, FLUTE);
  const noise = new Noise(n.seed);
  const breath = new Biquad("bandpass", f * 2, 4, sr);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const t = i / sr;
    const env = envelope(t, n.heldSec, FLUTE);
    if (env < 1e-4 && t > n.heldSec) break;
    // vibrato arrives after the note has spoken
    const vib = 1 + 0.004 * Math.min(1, t / 0.4) * Math.sin(2 * Math.PI * 5.5 * t);
    phase += (f * vib) / sr;
    const tone = sinTurns(phase) + 0.18 * sinTurns(phase * 2) + 0.05 * sinTurns(phase * 3);
    const air = breath.run(noise.next()) * (0.9 + 0.6 * Math.exp(-t / 0.08));
    out[i] = (tone + 0.35 * air) * 0.55 * env * (0.6 + 0.4 * n.gain);
  }
  return fade(out, sr);
}
